name: E2E Tests avec Playwright et Envoi de Rapports via Angular

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get install -y libgtk-4-1 libatomic1 libenchant-2-2 libmanette-0.2-0
          npx playwright install


      - name: Build de l'application Angular
        run: npm run build

      - name: Lancer le serveur Angular
        run: |
          nohup npx ng serve --port 4200 &
          sleep 15  # Attendre que le serveur soit opérationnel

      - name: Run Playwright tests
        run: |
          npx playwright test

      - name: Export Test Results
        run: |
          mkdir -p reports
          cp -r playwright-report/* reports/

      - name: Send test results to PractiTest
        run: |
          curl -H "PTToken: ce4752a1a0cf8fe2855ce4f1473fee388e4cbcd3" \
          -H "Content-Type: application/json" \
          -H "Accept: application/json" \
          "https://api.practitest.com/api/v2/projects/30786/runs"
